<!-- Footer Start -->
<footer class="footer bg-dark-footer relative text-gray-200 dark:text-gray-200">
    <div class="container relative">
        <div class="grid grid-cols-12">
            <div class="col-span-12">
                <div class="py-[60px] px-0">
                    <div class="grid md:grid-cols-12 grid-cols-1 gap-[30px]">
                        <div class="lg:col-span-4 md:col-span-12">
                            <a href="#" class="text-[22px] focus:outline-none">
                                <img src="/images/logo-light.png" alt="">
                            </a>
                            <p class="mt-6 text-gray-300">Start developing with Sukarix to create robust enterprise
                                PHP applications.</p>
                            <ul class="list-none mt-6">
                                <li class="inline"><a href="https://github.com/sukarix" target="_blank"
                                                      class="size-8 inline-flex items-center justify-center tracking-wide align-middle duration-500 text-base text-center border border-gray-800 rounded-md hover:border-purple-600 dark:hover:border-purple-600 hover:bg-purple-600 dark:hover:bg-purple-600"><i
                                                class="uil uil-github-alt align-middle" title="customization"></i></a>
                                </li>
                            </ul><!--end icon-->
                        </div><!--end col-->

                        <div class="lg:col-span-2 md:col-span-4">
                            <h5 class="tracking-[1px] text-gray-100 font-semibold">RIADVICE</h5>
                            <ul class="list-none footer-list mt-6">
                                <li><a href="https://riadvice.tn/about-us/" target="_blank"
                                       class="text-gray-300 hover:text-gray-400 duration-500 ease-in-out"><i
                                                class="uil uil-angle-right-b"></i> About us</a></li>
                            </ul>
                        </div><!--end col-->

                        <div class="lg:col-span-3 md:col-span-4">
                            <h5 class="tracking-[1px] text-gray-100 font-semibold">Built with Sukarix</h5>
                            <ul class="list-none footer-list mt-6">
                                <li><a href="https://zcaleright.com/" target="_blank"
                                       class="text-gray-300 hover:text-gray-400 duration-500 ease-in-out"><i
                                                class="uil uil-angle-right-b"></i> ZcaleRight</a></li>
                            </ul>
                        </div><!--end col-->

                    </div><!--end grid-->
                </div><!--end col-->
            </div>
        </div><!--end grid-->
    </div><!--end container-->

    <div class="py-[30px] px-0 border-t border-slate-800">
        <div class="container relative text-center">
            <div class="grid md:grid-cols-2 items-center">
                <div class="md:text-start text-center">
                    <p class="mb-0">©
                        <script>document.write(new Date().getFullYear())</script>
                        <a href="https://riadvice.tn">RIADVICE</a>. Built with <i
                                class="mdi mdi-heart text-red-600"></i> and <a
                                href="https://riadvice.tn/" target="_blank" class="text-reset">Sukarix</a>.
                    </p>
                </div>
            </div><!--end container-->
        </div>
    </div>
</footer><!--end footer-->
<!-- Footer End -->
