<footer id="footer">
    <div class="footer1">
        <div class="container">
            <div class="row">
                <div class="col-md-5 panel">
                    <h3 class="panel-title">About</h3>
                    <div class="panel-body">
                        <p>&copy; 2024 RIADVICE. All rights reserved.</p>
                    </div>
                </div>

                <div class="col-md-4 panel contact">
                    <h3 class="panel-title">Contact Info</h3>
                    <div class="panel-body">
                        <ul>
                            <li><a href="#"><i class="fa fa-envelope-o"></i> contact@riadvice.tn</a></li>
                        </ul>
                    </div>
                </div>

                <div class="col-md-3 panel">
                    <h3 class="panel-title">Follow us</h3>
                    <div class="panel-body">
                        <p class="follow-me-icons">
                            <a href="https://github.com/sukarix"><i class="fa fa-github fa-2"></i></a>
                        </p>
                    </div>
                </div>

            </div> <!-- /row of panels -->
        </div>
    </div>

    <div class="footer2">
        <div class="container">
            <div class="row">

                <div class="col-md-6 panel">
                    <div class="panel-body">
                        <p class="simplenav">
                            <a href="{{ @ALIASES.home }}">Home</a> |
                            <a href="https://sukarix.com/docs">Documentation</a> |
                        </p>
                    </div>
                </div>

                <div class="col-md-6 panel">
                    <div class="panel-body">
                        <p class="text-right">Template by <a href="http://webthemez.com" target="_blank">WebThemez</a>.
                            Licensed under <a href="http://creativecommons.org/licenses/by/3.0/" target="_blank">Creative
                                Commons Attribution 3.0</a>.</p>
                    </div>
                </div>

            </div> <!-- /row of panels -->
        </div>
    </div>

</footer>