<!-- Header -->
<header id="head">
    <div class="container">
        <div class="banner-content">
            <div id="da-slider" class="da-slider">
                <div class="da-slide">
                    <h2>Robust Foundation</h2>
                    <p>Built on years of development, Sukarix offers a robust foundation that handles various use cases
                        and edge scenarios gracefully, ensuring application stability.</p>
                    <div class="da-img"></div>
                </div>
                <div class="da-slide">
                    <h2>Stability Across PHP Upgrades</h2>
                    <p>Sukarix ensures stability and robustness across PHP upgrades, minimizing the need for extensive
                        refactoring and reducing risks during upgrades.</p>
                    <div class="da-img"></div>
                </div>
                <div class="da-slide">
                    <h2>Resource Efficiency</h2>
                    <p>Optimized for performance, Sukarix has a minimal footprint and consumes fewer resources, making
                        it ideal for high-performance applications.</p>
                    <div class="da-img"></div>
                </div>
                <div class="da-slide">
                    <h2>Usability and Practicality</h2>
                    <p>With a well-established history of stability and performance, Sukarix enhances the reliable
                        Fat-Free Framework to meet modern development needs.</p>
                    <div class="da-img"></div>
                </div>
                <nav class="da-arrows">
                    <span class="da-arrows-prev"></span>
                    <span class="da-arrows-next"></span>
                </nav>
            </div>
        </div>
    </div>
</header>
<!-- /Header -->