<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Atlanta is a modern and fully responsive Template by WebThemez.">
    <meta name="author" content="webThemez.com">
    <title>Sukarix - The Right Amount of Sweetness and Efficiency on Top of Fat-Free</title>
    <link rel="favicon" href="favicon.ico">
    <link rel="stylesheet" media="screen" href="http://fonts.googleapis.com/css?family=Open+Sans:300,400,700">
    <css src="bootstrap.min.css"/>
    <css src="font-awesome.min.css"/>
    <!-- Custom styles for our template -->
    <css src="font-awesome.min.css"/>
    <css src="bootstrap-theme.css"/>
    <css src="da-slider.css"/>
    <css src="style.css"/>
</head>
