<head>
    <meta charset="UTF-8">
    <title>Sukarix PHP Framework - The Right Amount of Sweetness and Efficiency on Top of Fat-Free</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Tailwind CSS Multipurpose Landing & Admin Dashboard Template">
    <meta name="keywords"
          content="agency, application, business, clean, creative, cryptocurrency, it solutions, modern, multipurpose, nft marketplace, portfolio, saas, software, tailwind css">
    <meta name="author" content="RIADVICE">
    <meta name="website" content="https://riadvice.tn">
    <meta name="email" content="contact@riadivce.tn">
    <meta name="version" content="2.2.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <!-- favicon -->
    <link rel="shortcut icon" href="favicon.ico">

    <!-- Css -->
    <css src="tiny-slider.css"/>
    <!-- Main Css -->
    <css src="line.css"/>
    <css src="materialdesignicons.min.css"/>
    <css src="tailwind.min.css"/>
</head>

<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-5DXC6NQBLR"></script>
<script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());

    gtag('config', 'G-5DXC6NQBLR');
</script>
