<js src="libs/jquery-3.7.1.min.js"/>


<!-- JAVASCRIPTS -->
<js src="libs/tiny-slider.min.js"/>
<js src="libs/feather.min.js"/>
<js src="plugins.init.js"/>
<js src="app.js"/>
<!-- JAVASCRIPTS -->

<js src="core/common.js"/>
<js src="core/locale.js"/>

{{ \Sukarix\Helpers\Assets::instance()->renderGroup('footer') }}

<script>
    jQuery(document).ready(function () {
        {{ \Sukarix\Helpers\Assets::instance()->currentJsLocale() }}
        {{ \Sukarix\Helpers\Assets::instance()->setUserRole() }}
        {{ \Sukarix\Helpers\Assets::instance()->initJsClasses() }}
    });
</script>
