<!-- Intro -->
<div class="container text-center">
    <br>
    <h2>Welcome to Sukarix: The Sweet Spot in PHP Development</h2>
    <p class="text-muted">
        The primary purpose of Sukarix is to provide developers with a powerful and efficient framework for building
        enterprise-level PHP applications.
    </p>
</div>
<!-- /Intro-->

<!-- Highlights - jumbotron -->
<div class="jumbotron top-space">
    <div class="container">

        <h3 class="text-center">Sweet Spot, just the right dosage!</h3>

        <div class="row">
            <div class="col-md-3 col-sm-6 highlight">
                <div class="h-caption"><h4><i class="fa fa-arrows-turn-to-dots fa-2x circle"></i>Routing & ACL</h4></div>
                <div class="h-body text-center">
                    <p>Sukarix offers advanced routing and ACL (Access Control List) capabilities, ensuring secure and
                        flexible access management for your applications.</p>
                </div>
            </div>
            <div class="col-md-3 col-sm-6 highlight">
                <div class="h-caption"><h4><i class="fa fa-file-code fa-2x circle"></i>Intuitive Template Engine</h4>
                </div>
                <div class="h-body text-center">
                    <p>Our intuitive template engine simplifies the process of rendering dynamic content, making it easy
                        to build responsive and interactive web pages.</p>
                </div>
            </div>
            <div class="col-md-3 col-sm-6 highlight">
                <div class="h-caption"><h4><i class="fa fa-cogs fa-2x circle"></i>Fat-Free Core</h4></div>
                <div class="h-body text-center">
                    <p>Sukarix is built on the reliable and lightweight Fat-Free Framework core, providing a robust
                        foundation for developing high-performance applications.</p>
                </div>
            </div>
            <div class="col-md-3 col-sm-6 highlight">
                <div class="h-caption"><h4><i class="fa fa-briefcase fa-2x circle"></i>Enterprise Ready</h4></div>
                <div class="h-body text-center">
                    <p>Designed for enterprise use, Sukarix ensures scalability, and performance, making it
                        the ideal choice for mission-critical applications.</p>
                </div>
            </div>
        </div> <!-- /row  -->


    </div>
</div>
<!-- /Highlights -->