<!-- Start Hero -->
<section
        class="relative table w-full py-36 lg:py-64 ltr:bg-[url('/images/bg.jpg')] rtl:bg-[url('/images/bg-rtl.jpg')] bg-no-repeat sm:bg-left bg-right overflow-hidden bg-cover">
    <div class="container relative z-1">
        <div class="grid md:grid-cols-12 grid-cols-1 items-center mt-10 gap-[30px]">
            <div class="md:col-span-7">
                <div class="md:me-6">
                    <span class="text-xl font-semibold">Sukarix</span>
                    <h4 class="font-bold lg:leading-normal leading-normal text-4xl lg:text-5xl mb-5 text-black dark:text-white">
                        <span class="relative">The PHP Framework <br/> For Crafting <span class="text-purple-600">Excellence</span>
                            <div class="absolute inset-x-0 bottom-2 h-1.5 bg-gradient-to-r from-purple-600 to-green-600"></div>
                        </span>
                    </h4>
                    <p class="text-slate-400 text-lg max-w-xl">
                        Develop solid PHP applications with a flexible and robust PHP entreprise-grade
                        framework designed to build exceptional business applications with ease and efficiency.
                    </p>
                    <div class="mt-6">
                        <a href="/docs"
                           class="py-2 px-5 inline-block font-semibold tracking-wide border align-middle duration-500 text-base text-center bg-purple-600 hover:bg-purple-700 border-purple-600 hover:border-purple-700 text-white rounded-md">
                            <i class="uil uil-brackets-curly align-middle" title="Get Started"></i>
                            Get Started</a>
                        </a>
                    </div>
                </div>
            </div><!--end col-->
        </div><!--end grid-->
    </div><!--end container-->

    <div class="absolute md:w-3/4 w-full top-1/2 -translate-y-1/2">
        <div class="absolute w-full h-[5000px] bg-slate-50 dark:bg-slate-800 md:opacity-100 opacity-90 top-1/2 -translate-y-1/2 md:-start-[10%] -start-[25%] ltr:rotate-12 rtl:-rotate-12"
             style="height:2800px!important"></div>
        <div class="absolute md:w-48 w-20 h-[5000px] bg-purple-600 top-1/2 -translate-y-1/2 md:end-[10%] -end-[1%] ltr:rotate-12 rtl:-rotate-12"
             style="height:2800px!important"></div>
    </div>
</section><!--end section-->
<!-- End Hero -->


<!-- Start Section-->
<section class="relative">
    <div class="container relative m-6">
        <div class="grid md:grid-cols-2 grid-cols-1 pb-8 items-center">
            <div>
                <h6 class="text-purple-600 text-sm font-bold uppercase mb-2">Features</h6>
                <h3 class="md:text-3xl md:leading-normal text-2xl leading-normal font-semibold mb-4 md:mb-0">
                    The open-source <br>PHP application framework <br>powered by Fat-Free!</h3>
            </div>
        </div><!--end grid-->


        <div class="grid lg:grid-cols-4 md:grid-cols-2 grid-cols-1 mt-8 gap-[30px]">
            <div class="group relative p-6 shadow dark:shadow-gray-800 hover:shadow-md dark:hover:shadow-gray-700 hover:bg-purple-600 dark:hover:bg-purple-600 duration-500 rounded-xl bg-white dark:bg-slate-900 overflow-hidden text-center">
                <div class="relative overflow-hidden text-transparent -m-3">
                    <i data-feather="hexagon"
                       class="size-24 fill-purple-600/5 group-hover:fill-white/10 mx-auto rotate-90"></i>
                    <div class="absolute top-2/4 -translate-y-2/4 start-0 end-0 mx-auto text-purple-600 rounded-xl group-hover:text-white duration-500 text-3xl flex align-middle justify-center items-center">
                        <i class="uil uil-shield-check"></i>
                    </div>
                </div>

                <div class="mt-6">
                    <a href="" class="text-lg font-medium group-hover:text-white duration-500">Stability</a>
                    <p class="text-slate-400 group-hover:text-white/50 duration-500 mt-3">Ensures consistency across PHP
                        versions.</p>
                </div>
            </div><!--end feature-->

            <div class="group relative p-6 shadow dark:shadow-gray-800 hover:shadow-md dark:hover:shadow-gray-700 hover:bg-purple-600 dark:hover:bg-purple-600 duration-500 rounded-xl bg-white dark:bg-slate-900 overflow-hidden text-center">
                <div class="relative overflow-hidden text-transparent -m-3">
                    <i data-feather="hexagon"
                       class="size-24 fill-purple-600/5 group-hover:fill-white/10 mx-auto rotate-90"></i>
                    <div class="absolute top-2/4 -translate-y-2/4 start-0 end-0 mx-auto text-purple-600 rounded-xl group-hover:text-white duration-500 text-3xl flex align-middle justify-center items-center">
                        <i class="uil uil-books"></i>
                    </div>
                </div>

                <div class="mt-6">
                    <a href="" class="text-lg font-medium group-hover:text-white duration-500">Best Libraries</a>
                    <p class="text-slate-400 group-hover:text-white/50 duration-500 mt-3">Implemented with top PHP
                        libraries for robust features.</p>
                </div>
            </div><!--end feature-->

            <div class="group relative p-6 shadow dark:shadow-gray-800 hover:shadow-md dark:hover:shadow-gray-700 hover:bg-purple-600 dark:hover:bg-purple-600 duration-500 rounded-xl bg-white dark:bg-slate-900 overflow-hidden text-center">
                <div class="relative overflow-hidden text-transparent -m-3">
                    <i data-feather="hexagon"
                       class="size-24 fill-purple-600/5 group-hover:fill-white/10 mx-auto rotate-90"></i>
                    <div class="absolute top-2/4 -translate-y-2/4 start-0 end-0 mx-auto text-purple-600 rounded-xl group-hover:text-white duration-500 text-3xl flex align-middle justify-center items-center">
                        <i class="uil uil-database"></i>
                    </div>
                </div>

                <div class="mt-6">
                    <a href="" class="text-lg font-medium group-hover:text-white duration-500">Cortex ORM</a>
                    <p class="text-slate-400 group-hover:text-white/50 duration-500 mt-3">Advanced ORM for efficient
                        database management.</p>
                </div>
            </div><!--end feature-->

            <div class="group relative p-6 shadow dark:shadow-gray-800 hover:shadow-md dark:hover:shadow-gray-700 hover:bg-purple-600 dark:hover:bg-purple-600 duration-500 rounded-xl bg-white dark:bg-slate-900 overflow-hidden text-center">
                <div class="relative overflow-hidden text-transparent -m-3">
                    <i data-feather="hexagon"
                       class="size-24 fill-purple-600/5 group-hover:fill-white/10 mx-auto rotate-90"></i>
                    <div class="absolute top-2/4 -translate-y-2/4 start-0 end-0 mx-auto text-purple-600 rounded-xl group-hover:text-white duration-500 text-3xl flex align-middle justify-center items-center">
                        <i class="uil uil-battery-bolt"></i>
                    </div>
                </div>

                <div class="mt-6">
                    <a href="" class="text-lg font-medium group-hover:text-white duration-500">Resource Efficient</a>
                    <p class="text-slate-400 group-hover:text-white/50 duration-500 mt-3">Optimised for minimal resource
                        usage.</p>
                </div>
            </div><!--end feature-->

            <div class="group relative p-6 shadow dark:shadow-gray-800 hover:shadow-md dark:hover:shadow-gray-700 hover:bg-purple-600 dark:hover:bg-purple-600 duration-500 rounded-xl bg-white dark:bg-slate-900 overflow-hidden text-center">
                <div class="relative overflow-hidden text-transparent -m-3">
                    <i data-feather="hexagon"
                       class="size-24 fill-purple-600/5 group-hover:fill-white/10 mx-auto rotate-90"></i>
                    <div class="absolute top-2/4 -translate-y-2/4 start-0 end-0 mx-auto text-purple-600 rounded-xl group-hover:text-white duration-500 text-3xl flex align-middle justify-center items-center">
                        <i class="uil uil-box"></i>
                    </div>
                </div>

                <div class="mt-6">
                    <a href="" class="text-lg font-medium group-hover:text-white duration-500">Container Mechanism</a>
                    <p class="text-slate-400 group-hover:text-white/50 duration-500 mt-3">Flexible dependency injection
                        and management.</p>
                </div>
            </div><!--end feature-->

            <div class="group relative p-6 shadow dark:shadow-gray-800 hover:shadow-md dark:hover:shadow-gray-700 hover:bg-purple-600 dark:hover:bg-purple-600 duration-500 rounded-xl bg-white dark:bg-slate-900 overflow-hidden text-center">
                <div class="relative overflow-hidden text-transparent -m-3">
                    <i data-feather="hexagon"
                       class="size-24 fill-purple-600/5 group-hover:fill-white/10 mx-auto rotate-90"></i>
                    <div class="absolute top-2/4 -translate-y-2/4 start-0 end-0 mx-auto text-purple-600 rounded-xl group-hover:text-white duration-500 text-3xl flex align-middle justify-center items-center">
                        <i class="uil uil-users-alt"></i>
                    </div>
                </div>

                <div class="mt-6">
                    <a href="" class="text-lg font-medium group-hover:text-white duration-500">Logging</a>
                    <p class="text-slate-400 group-hover:text-white/50 duration-500 mt-3">Powered by Monolog for
                        comprehensive logging.</p>
                </div>
            </div><!--end feature-->

            <div class="group relative p-6 shadow dark:shadow-gray-800 hover:shadow-md dark:hover:shadow-gray-700 hover:bg-purple-600 dark:hover:bg-purple-600 duration-500 rounded-xl bg-white dark:bg-slate-900 overflow-hidden text-center">
                <div class="relative overflow-hidden text-transparent -m-3">
                    <i data-feather="hexagon"
                       class="size-24 fill-purple-600/5 group-hover:fill-white/10 mx-auto rotate-90"></i>
                    <div class="absolute top-2/4 -translate-y-2/4 start-0 end-0 mx-auto text-purple-600 rounded-xl group-hover:text-white duration-500 text-3xl flex align-middle justify-center items-center">
                        <i class="uil uil-pathfinder"></i>
                    </div>
                </div>

                <div class="mt-6">
                    <a href="" class="text-lg font-medium group-hover:text-white duration-500">Routing & ACL</a>
                    <p class="text-slate-400 group-hover:text-white/50 duration-500 mt-3">Simple and powerful routing
                        and access control.</p>
                </div>
            </div><!--end feature-->

            <div class="group relative p-6 shadow dark:shadow-gray-800 hover:shadow-md dark:hover:shadow-gray-700 hover:bg-purple-600 dark:hover:bg-purple-600 duration-500 rounded-xl bg-white dark:bg-slate-900 overflow-hidden text-center">
                <div class="relative overflow-hidden text-transparent -m-3">
                    <i data-feather="hexagon"
                       class="size-24 fill-purple-600/5 group-hover:fill-white/10 mx-auto rotate-90"></i>
                    <div class="absolute top-2/4 -translate-y-2/4 start-0 end-0 mx-auto text-purple-600 rounded-xl group-hover:text-white duration-500 text-3xl flex align-middle justify-center items-center">
                        <i class="uil uil-brush-alt"></i>
                    </div>
                </div>

                <div class="mt-6">
                    <a href="" class="text-lg font-medium group-hover:text-white duration-500">Frontend Friendly</a>
                    <p class="text-slate-400 group-hover:text-white/50 duration-500 mt-3">Provides essential
                        implementation for frontend integration.</p>
                </div>
            </div><!--end feature-->
        </div>
    </div><!--end container-->
    <!-- End -->